site_name: SCALLOP-INF
repo_url: https://github.com/jinghuazhao/INF
edit_uri: ""
nav:
  - "": README.md
  - doc/SCALLOP_INF1_analysis_plan.md
  - Implementation:
    - tryggve/README.md
    - cardio/README.md
    - csd3/README.md
    - Supplementary notes: rsid/README.md
theme:
    name: mkdocs
    nav_style: dark
    highlightjs: true
    hljs_languages:
        - Bash
        - HTML
        - Java
        - JavaScript
        - Perl
        - Python
        - R
        - rust
        - yaml
plugins:
    - search
    - mermaid2
markdown_extensions:
  - toc:
    permalink: True
  - attr_list
  - footnotes
  - meta
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
