site_name: SCALLOP-INF
nav:
  - Home: README.md
  - doc/SCALLOP_INF1_analysis_plan.md
  - cardio/README.md
  - csd3/README.md
  - tryggve/README.md
  - rsid/README.md
  - doc/README.md
theme:
    name: mkdocs
    nav_style: dark
    highlightjs: true
    hljs_languages:
        - Bash
        - HTML
        - Java
        - JavaScript
        - Perl
        - Python
        - R
        - rust
        - yaml
plugins:
    - search
    - mermaid2
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
