# 11-9-2019 JHZ

options(digits=3, scipen=20, width=500)
k <- Sys.getenv("k")
pr <- Sys.getenv("pr")
snpid_rsid <- Sys.getenv("snpid_rsid")
cat(pr, "\n")
con <- file(paste0(pr, ".log_sss"))
log <- readLines(con)
close(con)
snp <- read.table(paste0(pr, ".snp"), as.is=TRUE, header=TRUE)
snp <- within(snp,{pos<-position/1e6})
png(paste0(pr,".png"),height=12,width=6,units="in",res=300)
par(mfrow=c(3,1))
with(snp, {
  lp <- -gap::log10p(beta/se)
  plot(pos,lp,cex=0.3,xlab="",ylab="-log10(P)",axes=FALSE)
  axis(2)
  plot(pos,prob,cex=0.3,xlab="",ylab="PIP",axes=FALSE)
  points(pos[prob>0.8],prob[prob>0.8],cex=0.3,col="red")
  axis(2)
  plot(pos,log10bf,cex=0.3,xlab="Position (MB)", ylab="log10(BF)", axes=FALSE)
  axis(1)
  axis(2)
})
dev.off()
config <- read.table(paste0(pr,".config"),as.is=TRUE,header=TRUE)
if (file.exists(paste0(pr,".cred"))) cred <- read.table(paste0(pr,".cred"),as.is=TRUE,header=TRUE)
load(paste0(snpid_rsid,".rda"))
library(openxlsx)
xlsx <- paste0(pr, "-finemap.xlsx")
unlink(xlsx, recursive = FALSE, force = TRUE)
wb <- createWorkbook(xlsx)
f <- make.names(pr)
addWorksheet(wb, "snpid_rsid")
writeDataTable(wb, "snpid_rsid", snpid_rsid)
addWorksheet(wb, paste0(f, ".log"))
writeDataTable(wb, paste0(f, ".log"), as.data.frame(log))
addWorksheet(wb, paste0(f, ".snp"))
snpk <- head(snp,k)
writeDataTable(wb, paste0(f, ".snp"), snpk)
addWorksheet(wb, "pip.plot")
insertImage(wb, "pip.plot", paste0(pr,".png"),height=12,width=8)
addWorksheet(wb, paste0(f, ".cfg"))
config1 <- head(config,1)
writeDataTable(wb, paste0(f, ".cfg"), config1)
if (exists("cred")) {
  addWorksheet(wb, "cred")
  writeDataTable(wb, "cred", cred)
}
saveWorkbook(wb, file=xlsx, overwrite=TRUE)
