# 7-9-2019 JHZ

options(digits=3, scipen=20, width=500)
pr <- Sys.getenv("pr")
snpid_rsid <- Sys.getenv("snpid_rsid")
cat(pr, "\n")
con <- file(paste0(pr, ".log_sss"))
log <- readLines(con)
close(con)
snp <- read.table(paste0(pr, ".snp"), as.is=TRUE, header=TRUE)
snp <- within(snp,{pos<-position/1e6})
png(paste0(pr,".png"),height=6,width=8,units="in",res=300)
with(snp, {
  plot(pos,prob,cex=0.4,xlab="Position (MB)",ylab="PIP")
  points(pos[prob>0.8],prob[prob>0.8],cex=0.4,col="red")
})
dev.off()
config <- read.table(paste0(pr,".config"),as.is=TRUE,header=TRUE)
cred <- read.table(paste0(pr,".cred"),as.is=TRUE,header=TRUE)
load(paste0(snpid_rsid,".rda"))
library(openxlsx)
xlsx <- paste0(pr, "-finemap.xlsx")
unlink(xlsx, recursive = FALSE, force = TRUE)
wb <- createWorkbook(xlsx)
f <- make.names(pr)
addWorksheet(wb, "snpid_rsid")
writeDataTable(wb, "snpid_rsid", snpid_rsid)
addWorksheet(wb, paste0(f, ".log"))
writeDataTable(wb, paste0(f, ".log"), as.data.frame(log))
addWorksheet(wb, paste0(f, ".snp"))
writeDataTable(wb, paste0(f, ".snp"), snp)
addWorksheet(wb, "pip.plot")
insertImage(wb, "pip.plot", paste0(pr,".png"),width=16,height=10)
addWorksheet(wb, paste0(f, ".cfg"))
writeDataTable(wb, paste0(f, ".cfg"), config)
addWorksheet(wb, paste0(f, ".cs"))
writeDataTable(wb, paste0(f, ".cs"), cred)
saveWorkbook(wb, file=xlsx, overwrite=TRUE)
