# 13-9-2019 JHZ

options(scipen=20, width=2000)
pr <- Sys.getenv("pr")
snpid_rsid <- Sys.getenv("snpid_rsid")
jma <- read.delim(paste0(pr,".jma.cojo"),as.is=TRUE)
ldr <- read.delim(paste0(pr,".ldr.cojo"), as.is=TRUE)
tbl <- jma[setdiff(names(jma),c("b","se","p"))]
load(paste0(snpid_rsid,".rda"))
library(gap)
cred <- cs(tbl, b="bJ", se="bJ_se", cutoff=0.95)
require(openxlsx)
xlsx <- paste0(pr,"-slct.xlsx")
wb <- createWorkbook(xlsx)
f <- make.names(pr)
addWorksheet(wb, "jma")
writeDataTable(wb, "jma", merge(snpid_rsid,jma,by.x="rsid",by.y="SNP"))
addWorksheet(wb, "ldr")
writeDataTable(wb, "ldr", merge(snpid_rsid,ldr,by.x="rsid",by.y="SNP"))
addWorksheet(wb, "cs")
writeDataTable(wb, "cs",  merge(snpid_rsid,cred,by.x="rsid",by.y="SNP"))
saveWorkbook(wb, file=xlsx, overwrite=TRUE)
